language: php
php:
- 5.6
- 5.5
install:
- composer install
env:
  global:
    - DB_HOST=localhost
    - DB_DATABASE=marketing_notifications
    - DB_USERNAME=postgres
    - APP_ENV=testing
    - APP_KEY=M0HYKpEoPSPnl7V4Ck6notarealkeyUx
before_script:
  - psql -c 'create database marketing_notifications_test;' -U postgres
  - php artisan migrate
